### ISSUE TITLE
Ghost ping osoby zmutowanej na #wyślij_ticket w momencie gdy ktoś otrzyma mute

### ISSUE THREAD

**Issue by defous96** [strata-czasu/hashira#15]
Raczej to funkcja tymczasowa, bo jeśli nowy bot będzie wysyłał na DM klikalny odnośnik do #wyślij_ticket, to ghost ping może nie być potrzebny.

**Comment by Daste745** [comment]
Mam ping kanału `#wyslij-ticket` w wiadomości od bota przy otrzymywaniu muta, więc ta funkcja nie jest już potrzebna.
