### ISSUE TITLE
Wyrzucanie z voicechatu po dostaniu mute

### ISSUE THREAD

**Issue by Daste745** [strata-czasu/hashira#73]
Aktualnie Bruno robi to za nas mimo tego, że nie nakładamy za jego pomocą mutów. Powinniśmy zaimplementować to w naszym bocie, żeby nie było sytuacji, gdzie wyciszony user może rozmawiać na voice.

TODO:
- [ ] Rozłączenie użytkownika z voice w momencie otrzymania mute (ze /mute lub menu kontekstowego)

**Comment by HKGx** [comment]
Wydaje się być fixnięte 
https://github.com/strata-czasu/hashira/blob/8350b2df7f11670ccc35f9e28fbfaa6a7daf4a67/apps/bot/src/moderation/util.ts#L48-L64
