### ISSUE TITLE
Usuwane muty nie powinny zawsze zmieniać taska w message queue

### ISSUE THREAD

**Issue by HKGx** [strata-czasu/hashira#77]
https://github.com/strata-czasu/hashira/blob/0999ce33abde6c78478dfa4d4e39b72d7cf03050/apps/bot/src/moderation/mutes.ts#L313

**Comment by Daste745** [comment]
https://strata-czasu.sentry.io/share/issue/29057dd9569c4a6c951547284c45f031/
